export enum TimelyAction {
  AddNewComment = "Add New Comment",
  AddNewTag = "Add New Tag",
  AddNewTask = "Add New Task",
  AddTagToTask = "Add Tag To Task",
  CancelTask = "Cancel Task",
  DeleteComment = "Delete Comment",
  DeleteTag = "Delete Tag",
  DeleteTask = "Delete Task",
  EditTag = "Edit Tag",
  FinishTask = "Finish Task",
  PauseTask = "Pause Task",
  RefreshTasks = "Refresh Tasks",
  RemoveTagFromTask = "Remove Tag From Task",
  ReopenFinishedTask = "Reopen Finished Task",
  RestoreCancelledTask = "Restore Cancelled Task",
  ResumeTask = "Resume Task",
  StartTask = "Start Task",
  EditComment = "Edit Comment",
  EditSettings = "Edit Settings",
  EditTask = "Edit Task",
  TimerElapsed = "Timer Elapsed",
}
