name: Build and Release Timely

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write # Required for creating releases

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install Ubuntu Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.1-dev \
                             build-essential \
                             curl \
                             wget \
                             file \
                             libxdo-dev \
                             libssl-dev \
                             libayatana-appindicator3-dev \
                             librsvg2-dev

      - name: Install Dependencies
        run: npm install

      - name: Install Tauri CLI
        run: npm install --global @tauri-apps/cli

      - name: Build Timely
        run: npm run tauri build

      - name: Archive Windows Artifacts
        if: runner.os == 'Windows'
        run: |
          echo "Archiving Windows artifacts..."
          Compress-Archive -Path src-tauri/target/release/bundle/msi/* -DestinationPath timely-windows.zip

      - name: Archive macOS Artifacts
        if: runner.os == 'macOS'
        run: |
          echo "Archiving macOS artifacts..."
          zip -r timely-macos.zip src-tauri/target/release/bundle/dmg

      - name: Archive Linux Artifacts
        if: runner.os == 'Linux'
        run: |
          echo "Archiving Linux artifacts..."
          zip -r timely-linux.zip src-tauri/target/release/bundle/appimage

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: timely-${{ matrix.os }}
          path: timely-*.zip

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Compress Downloaded Artifacts
        run: |
          echo "Compressing downloaded artifacts..."
          cd ./artifacts
          for dir in *; do
            if [ -d "$dir" ]; then
              echo "Compressing $dir..."
              zip -r "${dir}.zip" "$dir"
            fi
          done
          echo "Compressed artifacts:"
          ls -al

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: "./artifacts/*.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
